{
 "title": "Par champion",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "champion_name",
    "label": "Nom du champion",
    "query": "SELECT DISTINCT champion_name\nFROM lol_mart_datas.lol_kpi_stats_per_champion;"
   }
  ]
 },
 "panels": [
  {
   "title": "Indices de performance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  damage_index AS \"Carry\",\r\n  tanking_index AS \"Tanking\",\r\n  support_index AS \"Support\"\r\n  \r\nFROM \r\n  lol_mart_datas.lol_kpi_stats_per_champion\r\nWHERE \r\n  champion_name = '$champion_name'"
    }
   ]
  },
  {
   "title": "Le KDA - (Kill+Assist)/Mort",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  avg_kda AS \"KDA\"\r\nFROM \r\n  lol_mart_datas.lol_kpi_stats_per_champion\r\nWHERE \r\n  champion_name = '$champion_name'"
    }
   ]
  },
  {
   "title": "⚔️ Répartition des dégâts infligés par minute",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  avg_physical_damage_per_minute AS \"Dégâts physiques\",\r\n  avg_magic_damage_per_minute AS \"Dégâts magiques\",\r\n  avg_true_damage_per_minute AS \"Dégâts brute\"\r\nFROM \r\n  lol_mart_datas.lol_kpi_stats_per_champion\r\nWHERE champion_name = '$champion_name'"
    }
   ]
  },
  {
   "title": "🛡️Répartition des dégâts subis par minute",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  avg_physical_damage_taken_per_minute AS \"Dégâts physiques\",\r\n  avg_magic_damage_taken_per_minute AS \"Dégâts magiques\",\r\n  avg_true_damage_taken_per_minute AS \"Dégâts brute\"\r\nFROM \r\n  lol_mart_datas.lol_kpi_stats_per_champion\r\nWHERE \r\n  champion_name = '$champion_name'"
    }
   ]
  },
  {
   "title": "KDA par minute",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  avg_kills_per_minute AS \"Kill par minute\",\r\n  avg_deaths_per_minute AS \"Deaths par minute\",\r\n  avg_assists_per_minute AS \"Assists par minute\"\r\nFROM \r\n  lol_mart_datas.lol_kpi_stats_per_champion\r\nWHERE \r\n  champion_name = '$champion_name'"
    }
   ]
  },
  {
   "title": "Nombre de game (en base)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  total_games\r\nFROM \r\n  lol_mart_datas.lol_kpi_stats_per_champion\r\nWHERE \r\n  champion_name = '$champion_name'"
    }
   ]
  },
  {
   "title": "Multi-kill score (score pondéré des multi-kills)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  avg_multi_kill_score AS \"Score\"\r\nFROM \r\n  lol_mart_datas.lol_kpi_stats_per_champion\r\nWHERE \r\n  champion_name = '$champion_name'"
    }
   ]
  },
  {
   "title": "Farm et économie",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  avg_cs_per_minute AS \"Creeps par minute\",\r\n  avg_gold_per_minute AS \"Gold par minute\"\r\nFROM \r\n  lol_mart_datas.lol_kpi_stats_per_champion\r\nWHERE \r\n  champion_name = '$champion_name'"
    }
   ]
  },
  {
   "title": "Penta rate (pourcentage de parties avec penta)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  penta_rate AS \"Score\"\r\nFROM \r\n  lol_mart_datas.lol_kpi_stats_per_champion\r\nWHERE \r\n  champion_name = '$champion_name'"
    }
   ]
  }
 ]
}