{
 "title": "JeanPomme",
 "time": { "from": "2026-01-09T14:11:42.042Z", "to": "2026-01-09T20:11:53.920Z" },
 "panels": [
  {
   "title": "Top 10 des champions les plus joués",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  champion_name AS \"Nom du champion\",\r\n  total_games AS \"Nombre de game\"\r\nFROM lol_mart_datas.lol_kpi_stats_per_player_champion\r\nWHERE game_name = 'JeanPomme'\r\nORDER BY total_games DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Répartition des dégâts infligés par minute",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  avg_physical_damage_per_minute AS \"Dégâts physiques\",\r\n  avg_magic_damage_per_minute AS \"Dégâts magiques\",\r\n  avg_true_damage_per_minute AS \"Dégâts brute\"\r\nFROM \r\n  lol_mart_datas.lol_kpi_stats_per_player\r\nWHERE game_name = 'JeanPomme'"
    }
   ]
  },
  {
   "title": "Répartition des dégâts subis par minute",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  avg_physical_damage_taken_per_minute AS \"Dégâts physiques\",\r\n  avg_magic_damage_taken_per_minute AS \"Dégâts magiques\",\r\n  avg_true_damage_taken_per_minute AS \"Dégâts brute\"\r\nFROM \r\n  lol_mart_datas.lol_kpi_stats_per_player\r\nWHERE game_name = 'JeanPomme'"
    }
   ]
  },
  {
   "title": "KDA par minute",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  avg_kills_per_minute AS \"Kill par minute\",\r\n  avg_deaths_per_minute AS \"Deaths par minute\",\r\n  avg_assists_per_minute AS \"Assists par brute\"\r\nFROM \r\n  lol_mart_datas.lol_kpi_stats_per_player\r\nWHERE game_name = 'JeanPomme'"
    }
   ]
  },
  {
   "title": "Le KDA - (Kill+Assist)/Mort",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  avg_kda AS \"KDA\"\r\nFROM \r\n  lol_mart_datas.lol_kpi_stats_per_player\r\nWHERE game_name = 'JeanPomme'"
    }
   ]
  },
  {
   "title": "Dégâts par minute/champion",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  champion_name AS \"Nom du champion\",\r\n  avg_physical_damage_per_minute AS \"Dégâts physiques\",\r\n  avg_magic_damage_per_minute AS \"Dégâts magiques\",\r\n  avg_true_damage_per_minute AS \"Dégâts brute\"\r\n\r\nFROM lol_mart_datas.lol_kpi_stats_per_player_champion\r\nWHERE game_name = 'JeanPomme'\r\nORDER BY avg_damage_per_minute DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Indices de performance",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  tanking_index AS \"Tanking\",\r\n  damage_index AS \"Carry\",\r\n  support_index AS \"Support\"\r\n  \r\nFROM \r\n  lol_mart_datas.lol_kpi_stats_per_player\r\nWHERE game_name = 'JeanPomme'"
    }
   ]
  },
  {
   "title": "Farm et économie",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  avg_cs_per_minute AS \"Creeps par minute\",\r\n  avg_gold_per_minute AS \"Gold par minute\"\r\nFROM \r\n  lol_mart_datas.lol_kpi_stats_per_player\r\nWHERE game_name = 'JeanPomme'"
    }
   ]
  },
  {
   "title": "Multi-kill score (score pondéré des multi-kills)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  avg_multi_kill_score AS \"Score\"\r\n\r\nFROM \r\n\r\n  lol_mart_datas.lol_kpi_stats_per_player\r\n\r\nWHERE game_name = 'JeanPomme'"
    }
   ]
  },
  {
   "title": "Nombre de game (en base)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  total_games\r\nFROM \r\n  lol_mart_datas.lol_kpi_stats_per_player\r\nWHERE game_name = 'JeanPomme'"
    }
   ]
  },
  {
   "title": "Penta rate (pourcentage de parties avec penta)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  penta_rate AS \"Score\"\r\n\r\nFROM \r\n\r\n  lol_mart_datas.lol_kpi_stats_per_player\r\n\r\nWHERE game_name = 'JeanPomme'"
    }
   ]
  }
 ]
}