{
 "title": "Top champions",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Le KDA - (Kill+Assist)/Mort",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  avg_kda,\r\n  champion_name\r\nFROM lol_mart_datas.lol_kpi_stats_per_champion\r\nORDER BY avg_kda DESC\r\nLIMIT 20\r\n"
    }
   ]
  },
  {
   "title": "🎯Indices de performance - Carry",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  tanking_index, damage_index, support_index, \r\n  champion_name\r\nFROM lol_mart_datas.lol_kpi_stats_per_champion\r\nORDER BY damage_index DESC\r\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Dégâts infligés par minute",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n\tavg_damage_per_minute,\r\n\tchampion_name\r\nFROM lol_mart_datas.lol_kpi_stats_per_champion\r\nORDER BY avg_damage_per_minute DESC\r\nLIMIT 5\r\n"
    }
   ]
  },
  {
   "title": "⚔️ Répartition des dégâts physiques infligés par minute",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n\tavg_physical_damage_per_minute,\r\n\tchampion_name\r\nFROM lol_mart_datas.lol_kpi_stats_per_champion\r\nORDER BY avg_physical_damage_per_minute DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "🛡️Indices de performance - Tanking",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  tanking_index, damage_index, support_index, \r\n  champion_name\r\nFROM lol_mart_datas.lol_kpi_stats_per_champion\r\nORDER BY tanking_index DESC\r\nLIMIT 5"
    }
   ]
  },
  {
   "title": "💚Indices de performance - Support",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n  tanking_index, damage_index, support_index, \r\n  champion_name\r\nFROM lol_mart_datas.lol_kpi_stats_per_champion\r\nORDER BY support_index DESC\r\nLIMIT 5"
    }
   ]
  },
  {
   "title": "✨ Répartition des dégâts magiques par minute",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n\tavg_magic_damage_per_minute,\r\n\tchampion_name\r\nFROM lol_mart_datas.lol_kpi_stats_per_champion\r\nORDER BY avg_magic_damage_per_minute DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Multi-kill score (score pondéré des multi-kills)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n\r\navg_multi_kill_score,\r\nchampion_name\r\n\r\nFROM lol_mart_datas.lol_kpi_stats_per_champion\r\nORDER BY avg_multi_kill_score DESC\r\nLIMIT 5\r\n"
    }
   ]
  }
 ]
}