{
 "title": "Warehouse LOL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "puuid to process",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n\tgame_name,\r\n\ttag_line,\r\n\tdate_processed,\r\n\tCASE\r\n\t    WHEN date_processed = CURRENT_DATE THEN 1\r\n\t    ELSE 0\r\n\tEND AS processed_today\r\nFROM \r\n\tlol_fact_datas.lol_fact_puuid_to_process;"
    }
   ]
  },
  {
   "title": "fact match",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n\tCOUNT(match_id),\r\n\tCASE \r\n\t\tWHEN is_processed THEN 'processed'\r\n\t\tELSE 'not processed'\r\n\tEND is_processed\r\nFROM \r\n  lol_fact_datas.lol_fact_match\r\nGROUP BY \r\n\tCASE \r\n\t\tWHEN is_processed THEN 'processed'\r\n\t\tELSE 'not processed'\r\n\tEND\r\n\r\n\t"
    }
   ]
  },
  {
   "title": "fact puuid",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n\tCOUNT(puuid),\r\n\tCASE \r\n\t\tWHEN game_name IS NULL THEN 'not processed'\r\n\t\tELSE 'processed'\r\n\tEND is_processed\r\nFROM \r\n\tlol_fact_datas.lol_fact_puuid\r\nGROUP BY\r\n\tCASE \r\n\t\tWHEN game_name IS NULL THEN 'not processed'\r\n\t\tELSE 'processed'\r\n\tEND"
    }
   ]
  },
  {
   "title": "fact stats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n\tCOUNT(id)\r\nFROM \r\n\tlol_fact_datas.lol_fact_stats;"
    }
   ]
  },
  {
   "title": "fact match processed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n\tCOUNT(match_id)\r\nFROM \r\n  lol_fact_datas.lol_fact_match\r\nWHERE \r\n\tis_processed is true"
    }
   ]
  },
  {
   "title": "fact match NOT processed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n\tCOUNT(match_id)\r\nFROM \r\n  lol_fact_datas.lol_fact_match\r\nWHERE \r\n\tis_processed is false"
    }
   ]
  },
  {
   "title": "fact puuid processed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n\tCOUNT(puuid)\r\nFROM \r\n\tlol_fact_datas.lol_fact_puuid\r\nWHERE\r\n\tgame_name IS NOT NULL"
    }
   ]
  },
  {
   "title": "fact puuid NOT processed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "warehouse",
     "rawSql": "SELECT \r\n\tCOUNT(puuid)\r\nFROM \r\n\tlol_fact_datas.lol_fact_puuid\r\nWHERE\r\n\tgame_name IS NULL"
    }
   ]
  }
 ]
}